trigger:
  - master

pool:
  vmImage: ''macOS-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(System.DefaultWorkingDirectory)/pom.xml'
      mavenOptions: '-Xmx3072m'
      goals: 'clean package'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
