# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 1.0.0

pool:
  vmImage: macOS-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
