trigger:
  - 1.0.0

pool:
  vmImage: macOS-latest

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '18'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'Temurin'  # ✅ This avoids needing a file path

  - task: Maven@3
    inputs:
      mavenPomFile: '$(System.DefaultWorkingDirectory)/pom.xml'
      mavenOptions: '-Xmx3072m'
      goals: 'clean package'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '18'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
